# Generated by Django 3.0.6 on 2021-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('blogpost', models.CharField(max_length=10000)),
                ('createddatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
